//
//  HomeWorker.swift
//  DavitiKhvedelidzeHW28
//
//  Created by Dato Khvedelidze on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeWorkerLogic {
    func fetchCountryWeather(countryName: String) async throws -> City
}

final class HomeWorker: HomeWorkerLogic {
    // MARK: - Fields
    
    private var api: APIManager
    private var urlString = "https://api.openweathermap.org/data/2.5/weather"
    
    private var query = [URLQueryItem(name: "units", value: "metric"),
                         URLQueryItem(name: "appid", value: "58f0f97f547f2b174ebdaca4563236b0"),
                         URLQueryItem(name: "q", value: nil)]
    
    init(apiManager: APIManager) {
        self.api = apiManager
    }
    
    // MARK: - Methods
    
    func fetchCountryWeather(countryName: String) async throws -> City {
        query[2].value = countryName
        return try await api.fetchData(urlString: urlString, query: query, decodingType: City.self)
    }
}
