//
//  HomeModels.swift
//  DavitiKhvedelidzeHW28
//
//  Created by Dato Khvedelidze on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    // MARK: Use cases
    
    enum GetCountryWeather {
        struct Request {
            let countryName: String
        }
        
        struct Response { }
        
        struct ViewModel { }
    }
}
