//
//  HomeRouter.swift
//  DavitiKhvedelidzeHW28
//
//  Created by Dato Khvedelidze on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRoutingLogic {
    func routeToCountryWeatherDetails()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore { get }
}

class HomeRouter: HomeRoutingLogic, HomeDataPassing {
    // MARK: - Clean Components
    
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore
    
    // MARK: - Object Lifecycle
    
    init(dataStore: HomeDataStore) {
        self.dataStore = dataStore
    }
    
    // MARK: - Routing
    
    func routeToCountryWeatherDetails() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailsViewController") as! DetailsViewController
        var destinationDS = destinationVC.router!.dataStore!
        
        if dataStore.selectedCountry != nil {
            passDataToCountryWeatherDetails(source: dataStore, destination: &destinationDS)
            navigateToCountryWeatherDetails(source: viewController!, destination: destinationVC)
        }
    }
    
    func navigateToCountryWeatherDetails(source: HomeViewController, destination: DetailsViewController) {
        source.show(destination, sender: nil)
    }
    
    func passDataToCountryWeatherDetails(source: HomeDataStore, destination: inout DetailsDataStore) {
        destination.countryWeather = source.selectedCountry
    }
}
