//
//  HomeViewController.swift
//  DavitiKhvedelidzeHW28
//
//  Created by Dato Khvedelidze on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: AnyObject { }

class HomeViewController: UIViewController, HomeDisplayLogic {
    // MARK: - Clean Components
    
    var interactor: HomeBusinessLogic?
    var router: (HomeRoutingLogic & HomeDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup Relationships
    
    private func setup() {
        let apiManager = APIManager()
        let worker = HomeWorker(apiManager: apiManager)
        let presenter = HomePresenter()
        let interactor = HomeInteractor(presenter: presenter, worker: worker)
        let router = HomeRouter(dataStore: interactor)
        let viewController = self
        viewController.interactor = interactor
        viewController.router = router
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    // MARK: - Private Methods
    
    private func setupUI() {
        view.backgroundColor = UIColor.systemBlue
        titleLabel.text = "Enter desired city to get its weather, first press button fetch weather, wait couple seconds and then press show the results"
        titleLabel.numberOfLines = 0
        titleLabel.font = UIFont(name: "Futura", size: 20)
        titleLabel.textAlignment = .center
        
        countryTextField.textAlignment = .center
        
        fetchWeatherButtonOutlet.setTitle("Fetch weather", for: .normal)
        fetchWeatherButtonOutlet.layer.cornerRadius = 15
        fetchWeatherButtonOutlet.clipsToBounds = false
        fetchWeatherButtonOutlet.tintColor = UIColor.white
        fetchWeatherButtonOutlet.backgroundColor = UIColor.systemPink
        
        showWeatherDetailsButtonOutlet.setTitle("Show the results", for: .normal)
        showWeatherDetailsButtonOutlet.layer.cornerRadius = 15
        showWeatherDetailsButtonOutlet.clipsToBounds = false
        showWeatherDetailsButtonOutlet.tintColor = UIColor.white
        showWeatherDetailsButtonOutlet.backgroundColor = UIColor.systemPink
        
    }
    
    // MARK: - Outlets
    
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var countryTextField:UITextField!
    @IBOutlet weak var fetchWeatherButtonOutlet: UIButton!
    @IBOutlet weak var showWeatherDetailsButtonOutlet: UIButton!
    
    // MARK: - Button Actions
    
    @IBAction func fetchWeatherButtonAction(_ sender: Any) {
        interactor?.getCountryWeather(request: Home.GetCountryWeather.Request(countryName: countryTextField.text ?? "123"))
    }
    
    @IBAction func showWeatherDetailsButtonAction(_ sender: Any) {
        router?.routeToCountryWeatherDetails()
    }
}
