//
//  DetailsViewController.swift
//  DavitiKhvedelidzeHW28
//
//  Created by Dato Khvedelidze on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsDisplayLogic: AnyObject {
    func displayWeatherDetails(viewModel: Details.ShowWeatherDetails.ViewModel)
}

class DetailsViewController: UIViewController {
    // MARK: - Clean Components
    
    var interactor: DetailsBusinessLogic?
    var router: (NSObjectProtocol & DetailsRoutingLogic & DetailsDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup Relationships
    
    private func setup() {
        let viewController = self
        let presenter = DetailsPresenter()
        let interactor = DetailsInteractor(presenter: presenter)
        let router = DetailsRouter()
        viewController.interactor = interactor
        viewController.router = router
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        let request = Details.ShowWeatherDetails.Request()
        interactor?.getWeatherDetails(request: request)
    }
    
    // MARK: - Private Methods
    
    private func setupUI() {
        view.backgroundColor = UIColor.systemBlue
        navigationController?.navigationBar.tintColor = UIColor.black
        
        countryName.numberOfLines = 0
        countryName.font = UIFont(name: "Futura", size: 20)
        countryName.textAlignment = .center
        
        countryTemp.numberOfLines = 0
        countryTemp.font = UIFont(name: "Futura", size: 20)
        countryTemp.textAlignment = .center
    }
    
    // MARK: Outlets
    
    @IBOutlet weak var countryName: UILabel!
    @IBOutlet weak var countryTemp: UILabel!
    
}

// MARK: - DetailsDisplayLogic

extension DetailsViewController: DetailsDisplayLogic {
    func displayWeatherDetails(viewModel: Details.ShowWeatherDetails.ViewModel) {
        countryName.text = "The current weather in \(viewModel.cityName) is"
        countryTemp.text = "\(viewModel.cityWeather)°"
    }
}   
