//
//  DetailsPresenter.swift
//  DavitiKhvedelidzeHW28
//
//  Created by Dato Khvedelidze on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func presentWeatherDetails(response: Details.ShowWeatherDetails.Response)
}

final class DetailsPresenter {
    weak var viewController: DetailsDisplayLogic?
}

// MARK: - DetailsPresentationLogic

extension DetailsPresenter: DetailsPresentationLogic {
    func presentWeatherDetails(response: Details.ShowWeatherDetails.Response) {
        let cityName = response.city.name
        let cityWeather = round(response.city.main.temp)
        
        let viewModel = Details.ShowWeatherDetails.ViewModel(cityName: cityName, cityWeather: cityWeather)
        viewController?.displayWeatherDetails(viewModel: viewModel)
    }
}
