//
//  DetailsInteractor.swift
//  DavitiKhvedelidzeHW28
//
//  Created by Dato Khvedelidze on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
    func getWeatherDetails(request: Details.ShowWeatherDetails.Request)
}

protocol DetailsDataStore {
    var countryWeather: City? { get set }
}

class DetailsInteractor: DetailsDataStore {
    // MARK: - Clean Components
    
    private let presenter: DetailsPresentationLogic
    var countryWeather: City?
    
    // MARK: - Object Lifecycle
    
    init(presenter: DetailsPresentationLogic) {
        self.presenter = presenter
    }
}

// MARK: - DetailsBusinessLogic

extension DetailsInteractor: DetailsBusinessLogic {
    func getWeatherDetails(request: Details.ShowWeatherDetails.Request) {
        let response = Details.ShowWeatherDetails.Response(city: countryWeather!)
        presenter.presentWeatherDetails(response: response)
    }
}

