//
//  DetailsRouter.swift
//  DavitiKhvedelidzeHW28
//
//  Created by Dato Khvedelidze on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsRoutingLogic { }

protocol DetailsDataPassing {
    var dataStore: DetailsDataStore? { get }
}

final class DetailsRouter: NSObject, DetailsRoutingLogic, DetailsDataPassing {
    // MARK: - Clean Components
    
    weak var viewController: DetailsViewController?
    var dataStore: DetailsDataStore?
    
}
